package br.com.compass.filmes.cliente.enums;

public enum GenresEnum {
    ACAO, AVENTURA, ANIMACAO,
    COMEDIA, CRIME, DOCUMENTARIO,
    DRAMA, FAMILIA, FANTASIA,
    HISTORIA, TERROR, MUSICA,
    MISTERIO, ROMANCE, FICCAO_CIENTIFICA,
    CINEMA_TV, THIILLER, GUERRA,
    FAROESTE;
}
