package br.com.compass.filmes.user.enums;

public enum ProvidersEnum {
    NETFLIX, AMAZON_PRIME_VIDEO, AMAZON_PRIME, APPLE_ITUNES,
    GOOGLE_PLAY_MOVIES, SUN_NXT, MUBI, LOOKE, CLASSIX, STAR_PLUS,
    PARAMOUNT_PLUS, HBO_MAX, ARGO, EVENTIVE, CULTPIX, CLARO_VIDEO,
    TELECINE_PLAY, GLOBOPLAY, APPLE_TV_PLUS, AMAZON_VIDEO, FILMBOX,
    VIX, CURIOSITY_STREAM, SPAMFLIX, FUNIMATION_NOW, DOCSVILLE, NETMOVIES,
    STARZ_PLAY_AMAZON_CHANNEL, WOW_PRESENTS_PLUS, MAGELLAN_TV, PARAMOUNT_AMAZON_CHANNEL,
    BROADWAYHD, BELAS_ARTES_A_LA_CARTE, FILMZIE, DEKKO, BELIEVE, TRUE_STORY,
    HBO_GO, DOCALLIANCE_FILMS, HOICHOI, KOREAONDEMAND, OLDFLIX, PLUTO_TV,
    TNTGO, GOSPEL_PLAY, DISNEY_PLUS, NOW, LIBREFLIX, SUPO_MUNGAM_PLUS, FILME_FILME,
    STARZ, KINOPOP, OI_PLAY, MGM_AMAZON_CHANNEL, MICROSOFT_STORE, LOOKE_AMAZON_CHANNEL,
    REVRY, MOVIESAINTS;
}
