.env:
  directory: .
  filename: .env
  prefix: ""

security:
  jwt:
    token:
      secret-key: AwssW321F
      expire-length: 3600000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${URI}
      database: FilmesApollo70
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITUSERNAME}
    password: ${RABBITPASSWORD}

custom:
  movie-manager-url: http://localhost:8081/api/movie-manager
  allocation-history-url: http://localhost:8082/api/allocation-history